
describe('Check the site. Check the form in both desktop and mobile views', () => {
    const visitFormPage = () => {
        cy.visit('https://demoqa.com/automation-practice-form')
            .wait(5000)
    }

    it('test form in desktop and mobile views', () => {
        visitFormPage()

        cy.get('#firstName').should("be.visible")
            .type("Alice")
        cy.get('#lastName').should("be.visible")
            .type("QA")
            .wait(2000)
        cy.get('#userEmail').should("be.visible")
            .type("qa.exist@gmail.com")

        cy.get('#genterWrapper > .col-md-9 > :nth-child(3)').should("be.visible")
            .click()
        cy.get('#genterWrapper > .col-md-9 > :nth-child(3)').should("be.visible")
            .click()
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)').should("be.visible")
            .click()
            .wait(2000)

        cy.get('#userNumber').should("be.visible")
            .type("4923658274")
        cy.get('#dateOfBirthInput').should("be.visible").click()
            .wait(2000)
        cy.get('.react-datepicker__month-select').select('February')
            .wait(2000)
        cy.get('.react-datepicker__year-select').select('1913')
        cy.get(':nth-child(2) > .react-datepicker__day--007').click()
            .wait(1000)

        cy.get('.subjects-auto-complete__value-container').should("be.visible")
            .type("Test Text")
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').should("be.visible").click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').should("be.visible").click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').should("be.visible").click()
        cy.get('#uploadPicture').should("be.visible").click()
        cy.get('#currentAddress').should("be.visible").type("street 32")
            .wait(1000)

        cy.get('.css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r').should("be.visible").click()
            .type('{downarrow}{enter}')
            .wait(1000)
        cy.get('#city > .css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').should("be.visible").click()
            .type('{downarrow}{enter}')
            .wait(1000)
        cy.get('#submit').click()
        cy.screenshot()
            .wait(1000)
        cy.get('#closeLargeModal').scrollIntoView().click()


        cy.viewport('iphone-x')

        visitFormPage()

        cy.get('#firstName').should("be.visible")
            .type("Alice")
        cy.get('#lastName').should("be.visible")
            .type("QA")
            .wait(2000)
        cy.get('#userEmail').should("be.visible")
            .type("qa.exist@gmail.com")

        cy.get('#genterWrapper > .col-md-9 > :nth-child(3)').should("be.visible")
            .click()
        cy.get('#genterWrapper > .col-md-9 > :nth-child(3)').should("be.visible")
            .click()
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)').should("be.visible")
            .click()
            .wait(2000)

        cy.get('#userNumber').should("be.visible")
            .type("4923658274")
        cy.get('#dateOfBirthInput').should("be.visible").click()
            .wait(2000)
        cy.get('.react-datepicker__month-select').select('February')
            .wait(2000)
        cy.get('.react-datepicker__year-select').select('1913')
        cy.get(':nth-child(2) > .react-datepicker__day--007').click()
            .wait(1000)

        cy.get('.subjects-auto-complete__value-container').should("be.visible")
            .type("Test Text")
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').should("be.visible").click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2) > .custom-control-label').should("be.visible").click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').should("be.visible").click()
        cy.get('#uploadPicture').should("be.visible").click()
        cy.get('#currentAddress').should("be.visible").type("street 32")
            .wait(1000)

        cy.get('.css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer > .css-19bqh2r').should("be.visible").click()
            .type('{downarrow}{enter}')
            .wait(1000)
        cy.get('#city > .css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').should("be.visible").click()
            .type('{downarrow}{enter}')
            .wait(1000)
        cy.get('#submit').click()
        cy.screenshot()
            .wait(1000)
        cy.get('#closeLargeModal').scrollIntoView().click()
    })
})